name: Format Check

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install black isort
        
    - name: Run Black
      run: |
        INCLUDE_FOLDS=("flagscale" "tests")
        INCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${INCLUDE_FOLDS[@]}")
        EXCLUDE_FOLDS=("megatron/megatron/core" "megatron/megatron/inference")
        EXCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${EXCLUDE_FOLDS[@]}")
        
        include_files=""
        for file in $INCLUDE_FILES; do
            include_files+="$file|"
        done
        include_files=${include_files::-1}
        echo "$include_files"

        exclude_files=""
        for file in $EXCLUDE_FILES; do
            exclude_files+="$file|"
        done
        exclude_files=${exclude_files::-1}
        echo "$exclude_files"
        
        black --include '$include_files' --exclude '$exclude_files' --diff .

    - name: Run Isort
      run: |
        INCLUDE_FOLDS=("flagscale" "tests")
        INCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${INCLUDE_FOLDS[@]}")
        EXCLUDE_FOLDS=("megatron/megatron/core" "megatron/megatron/inference")
        EXCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${EXCLUDE_FOLDS[@]}")
        
        echo "$INCLUDE_FILES"
        skip_files=""
        for file in $EXCLUDE_FILES; do
            skip_files+="--skip $file "
        done
        echo "$skip_files"
        
        echo "isort --profile black '$INCLUDE_FILES' '$skip_files'"
        isort --profile black '$INCLUDE_FILES' '$skip_files'
