name: Format Check

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install black isort

    - name: Get Included Python Files
      id: get_include_files
      run: |
        INCLUDE_FOLDS=("flagscale" "tests")
        INCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${INCLUDE_FOLDS[@]}")

        EXCLUDE_FOLDS=("megatron/megatron/core" "megatron/megatron/inference")
        EXCLUDE_FILES=$(bash tests/scripts/format_tests/search_py_files.sh "${EXCLUDE_FOLDS[@]}")

        echo "include_files='$INCLUDE_FILES'" >> $GITHUB_ENV
        echo "exclude_files='$EXCLUDE_FILES'" >> $GITHUB_ENV
        
    - name: Run Black
      run: |
        _include_files=""
        for file in $include_files; do
            _include_files+="$file|"
        done
        echo "$_include_files"

        _exclude_files=""
        for file in $exclude_files; do
            _exclude_files+="$file|"
        done
        echo "$_exclude_files"
        
        black --include "$_include_files" --exclude "$_exclude_files" --diff .

    - name: Run Isort
      run: |
        echo "$include_files"
        _skip_files=""
        for file in $exclude_files; do
            _skip_files+="--skip $file "
        done
        isort --profile black "$include_files" $_skip_files
